### ISSUE TITLE
How do you compile the code

### ISSUE THREAD

**Issue by zinov** [GeorgDangl/Dangl.Calculator#2]
I am struggling how to compile the Lexer and the parser, I took your example and download it and compile it. That works. If I go under the obj folder and take any of the frameworks folders and get the generated files and replace the existing ones, they don't compile. 
If I am planning to start only from the .g4 file which are the steps you recommend to compile the generated code?

**Comment by GeorgDangl** [comment]
Hi @zinov, thanks for raising that issue!

Basically, the `Calculator.g4` file is the ANTLR grammar for the lexer and parser (see [official repo](https://github.com/tunnelvisionlabs/antlr4cs)). When you compile the `Dangl.Calculator` project, temporary code is generated by ANTLR and placed in the `obj` folder. But you shouldn't do changes there, since they're getting overwritten.

If you want to change the generated code by ANTLR, you should work with the `Calculator.g4` file.

So when you clone this repository, all you need is either the dotnet CLI or Visual Studio 2017 (or newer) to compile. Are you getting any compilation errors?

**Comment by GeorgDangl** [comment]
Hey @zinov, I'm closing this issue for now. If there's any further clarification needed, fell free to ask and I'll reopen.

**Comment by zinov** [comment]
@GeorgDangl sorry for not replying before, It took me time to understand that all the content was generated as part of the assembly and I didn't need to import those classes.(Lexer and Parser)
Thanks for your help
