### ISSUE TITLE
122-121.99 resolves to 0.010000000000051

### ISSUE THREAD

**Issue by mklierman** [GeorgDangl/Dangl.Calculator#3]

**Comment by GeorgDangl** [comment]
Hey @mklierman, thank you for raising this issue!

That is actually expected behavior, since the calculator does use doubles internal (and in the public API).
You can not represent arbitrary values with floating point types, see for example this dotnetfiddle:
https://dotnetfiddle.net/fbiXym
It’s probably a good idea to implement rounding to whatever significance you need in your app. 

I wouldn’t mind a PR that adds support for decimals, though😀
