### ISSUE TITLE
.NET 5

### ISSUE THREAD

**Issue by Xwilarg** [GeorgDangl/Dangl.Calculator#8]
Hey,
Any plan to update this to .NET 5?

**Comment by GeorgDangl** [comment]
Hey @Xwilarg, thank you for your issue!

The project is already targeting `netstandard2.0`, so it's compatible with .NET 5. We're also using it in lots of .NET 5 projects, so everything should work😀

Is there something that's not working for you?

**Comment by Xwilarg** [comment]
Thanks for your quick reply, I was more asking that because of the huge amount of dependencies but at the end I'm not that sure it's related (in some projects I have the issues, in some others I don't)
![image](https://user-images.githubusercontent.com/20053454/126896415-43ae8533-5a38-43ad-873c-384930341037.png)

**Comment by GeorgDangl** [comment]
I see, that looks like a lot of dependencies😀 Can you check which target your app resolves for `Dangl.Calculator`, is it using the `netstandard2.0` or the `netstandard1.1` one?

**Comment by Xwilarg** [comment]
Um.. May I ask you how I can do that?

**Comment by GeorgDangl** [comment]
Good question, I don’t know😀
It seems to import the NET Standard Library 1.6, which seems a bit strange. I think that one has all the other dependncies. You are just targeting ’net5.0’ in your app, right? 
Maybe that dependency comes from the Antlr4.Runtime package.

**Comment by Xwilarg** [comment]
I tried with 2 projects that both target .NET 5 but only have of them have this issue so I'm not sure what I'm doing wrong

**Comment by GeorgDangl** [comment]
Can you share the project?

**Comment by Xwilarg** [comment]
Sure it's this one: https://github.com/Xwilarg/Camellia/

**Comment by GeorgDangl** [comment]
Looks like the calculator isn't referenced there yet😀 But otherwise the project looks fine, nothing wrong as far as I can see that would cause this issue.

**Comment by Xwilarg** [comment]
Yup I opened the issue before referencing it but if you try to add the NuGet package you'll have the issue I'm speaking about

**Comment by GeorgDangl** [comment]
Ah, that was easy to resolve then😀

The many dependencies come in transitively from the `Antlr4.Runtime` package. If you just install this one (without `Dangl.Calculator`), you see the same behavior:
![image](https://user-images.githubusercontent.com/10274404/126981260-e910db18-d8bd-43f6-ab64-b071b451716a.png)

The issue seems to come from how `Antlr4.Runtime` has configured it's dependencies:
![image](https://user-images.githubusercontent.com/10274404/126981321-65fff9fd-30a3-42f7-96af-5eb3e5c4bf2a.png)

As you can see, the only dependency compatible to `net5.0` is `netstandard1.1`, which itself required the `NETStandard.Library`, thus including all the dependencies.

I don't think this is not going to cause any issues, since as far as I remember, the .NET Standard Library dependency is handled somehow different by .NET Core, it was something introduced for compatibility reasons or such.

**Comment by Xwilarg** [comment]
Okay I'll do that then
I'm also closing this issue since the issue is solved, thanks a lot for your time
